name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20.5

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Run Tests
        run: go test --cover ./src/...

  vet:
    name: Run vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20.5

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Run vet
        run: "go vet ./..."


  check:
    name: Run staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20.5

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Run static check
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.3"
          install-go: false
          cache-key: ${{ matrix.go }}
